apiVersion: apps/v1
kind: Deployment
metadata:
  name: wargame-db
spec:
  selector:
    matchLabels:
      app: wargame-db
  template:
    metadata:
      labels:
        app: wargame-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:latest
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        - name: MYSQL_DATABASE
          value: "LED_WG"
        - name: MYSQL_USER
          value: "wargame"
        - name: MYSQL_PASSWORD
          value: "1234"
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "no"
        - name: MYSQL_ROOT_HOST
          value: "%"
        volumeMounts:
        - name: mariadb-init
          mountPath: /docker-entrypoint-initdb.d
      volumes:
      - name: mariadb-init
        configMap:
          name: mariadb-init
